# sources.yml -- Silver layer tables consumed by dbt
#
# These tables are created by Spark (bronze_to_silver.py).
# dbt reads them to build the Gold star schema.
#
# Reference in models: {{ source('silver', 'daily_prices') }}
# Resolves to: cryptolake.silver.daily_prices

version: 2

sources:
  - name: silver
    description: "Lakehouse Silver layer -- cleaned and deduplicated data"
    schema: silver
    tables:
      - name: daily_prices
        description: "Daily prices per cryptocurrency, deduplicated and validated"
        columns:
          - name: coin_id
            description: "Cryptocurrency identifier (e.g. bitcoin, ethereum)"
          - name: price_date
            description: "Price date (DATE type)"
          - name: price_usd
            description: "Price in US dollars"
          - name: market_cap_usd
            description: "Market capitalization in USD"
          - name: volume_24h_usd
            description: "24-hour trading volume in USD"
          - name: _processed_at
            description: "Silver processing timestamp"

      - name: fear_greed
        description: "Crypto market Fear & Greed Index (0-100)"
        columns:
          - name: index_date
            description: "Index date"
          - name: fear_greed_value
            description: "Numeric value (0=Extreme Fear, 100=Extreme Greed)"
          - name: classification
            description: "Sentiment text classification"
          - name: _processed_at
            description: "Processing timestamp"
