# ============================================================
# sources.yml — Definición de datos de entrada para dbt
# ============================================================
# Un "source" en dbt es una tabla que ya existe en tu base de datos
# y que dbt NO crea ni gestiona. Solo la lee.
#
# En nuestro caso, las tablas Silver son creadas por los scripts
# de Spark (bronze_to_silver.py). dbt las lee para construir Gold.
#
# En los modelos SQL, las referenciamos así:
#   {{ source('silver', 'daily_prices') }}
#   → se traduce a: silver.daily_prices
#   → que Spark resuelve como: cryptolake.silver.daily_prices
# ============================================================

version: 2

sources:
  - name: silver
    description: "Capa Silver del Lakehouse — datos limpios y deduplicados"
    schema: silver
    tables:
      - name: daily_prices
        description: "Precios diarios por criptomoneda, deduplicados y validados"
        columns:
          - name: coin_id
            description: "Identificador único de la criptomoneda (ej: bitcoin, ethereum)"
          - name: price_date
            description: "Fecha del precio (tipo DATE)"
          - name: price_usd
            description: "Precio en dólares estadounidenses"
          - name: market_cap_usd
            description: "Capitalización de mercado en USD"
          - name: volume_24h_usd
            description: "Volumen de trading en las últimas 24 horas"
          - name: _processed_at
            description: "Timestamp de cuándo se procesó este registro en Silver"

      - name: fear_greed
        description: "Índice Fear & Greed del mercado crypto (0-100)"
        columns:
          - name: index_date
            description: "Fecha del índice"
          - name: fear_greed_value
            description: "Valor numérico (0=Extreme Fear, 100=Extreme Greed)"
          - name: classification
            description: "Clasificación textual del sentimiento"
          - name: _processed_at
            description: "Timestamp de procesamiento"
