# schema.yml -- Tests and documentation for marts models
#
# Generic dbt tests: not_null, unique, accepted_values, relationships.
# A test PASSES if the generated query returns 0 rows.

version: 2

models:
  - name: fact_market_daily
    description: "Daily crypto market metrics fact table. Granularity: 1 coin x 1 day."
    columns:
      - name: coin_id
        description: "Cryptocurrency identifier"
        tests:
          - not_null
      - name: price_date
        description: "Date of the record"
        tests:
          - not_null
      - name: price_usd
        description: "Price in USD"
        tests:
          - not_null

  - name: dim_coins
    description: "Cryptocurrency dimension with aggregate statistics (SCD Type 1)"
    columns:
      - name: coin_id
        description: "Unique cryptocurrency identifier"
        tests:
          - unique
          - not_null
      - name: all_time_high
        tests:
          - not_null
      - name: total_days_tracked
        tests:
          - not_null

  - name: dim_dates
    description: "Calendar dimension with temporal attributes"
    columns:
      - name: date_day
        description: "Date (primary key)"
        tests:
          - unique
          - not_null
