# dbt_project.yml -- CryptoLake dbt configuration
# Docs: https://docs.getdbt.com/reference/dbt_project.yml

name: cryptolake
version: '1.0.0'
config-version: 2

profile: cryptolake

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]

clean-targets:
  - target
  - dbt_packages

# Materialization strategy per folder
models:
  cryptolake:
    # staging/ -> Ephemeral (not persisted, always fresh)
    staging:
      +materialized: ephemeral
      +schema: staging

    # marts/ -> Physical tables (star schema for analytics)
    marts:
      +materialized: table
      +schema: gold

# Create Iceberg namespaces before model execution
on-run-start:
  - "CREATE NAMESPACE IF NOT EXISTS cryptolake.staging"
  - "CREATE NAMESPACE IF NOT EXISTS cryptolake.gold"
