# profiles.yml -- dbt connection configuration
#
# Targets:
#   dev:  local development (localhost:10000)
#   prod: Docker environment (spark-thrift:10000, used by Airflow)
#   ci:   compile-only, no Spark connection required

cryptolake:
  target: dev

  outputs:
    dev:
      type: spark
      method: thrift
      host: localhost
      port: 10000
      schema: gold
      auth: NOSASL
      threads: 1

    prod:
      type: spark
      method: thrift
      host: spark-thrift
      port: 10000
      schema: gold
      auth: NOSASL
      threads: 2

    ci:
      type: spark
      method: thrift
      host: localhost
      port: 10000
      schema: gold
      threads: 1
